### ISSUE TITLE
Folder does exist but no in-game change.

### ISSUE THREAD

**Issue by Ledfuld** [Eisbison/TheOtherHats#3]
Hello, I do have this TheOtherHats folder and all the files within my Among Us game location( steam version), but there isn't any in-game new hat I can choose.
Is there any possible reason or solution?

**Comment by dwd0tcom** [comment]
One solution can be a complete reinstall of Among Us and the mod. Did you try this?

**Comment by Ledfuld** [comment]
Yes, I uninstall Among Us and delete the folder. Do I need to do anything else like cleaning up the registry?

**Comment by dwd0tcom** [comment]
Sorry, I totally forgot your issue. Did you fix it somehow?
