### ISSUE TITLE
A question (for help)

### ISSUE THREAD

**Issue by TianMengLucky** [Eisbison/TheOtherHats#4]
Can I ask how to get the reshash in the json file and what it is used for, I want to add caps to my library but I don't know much about it?

**Comment by ccir2429** [comment]
Maybe ask in the discord server: https://dsc.gg/TheOtherRoles

**Comment by jellycooker** [comment]
> 

I think "reshash" means "resource hash"
The value of parameter "reshash" in json file is the MD5 value of your hat,
"reshasha" means Main texture,  "reshashc" means Climb texture, and so on
Every file has its own MD5 value, it just like its ID
here shows how it use:https://github.com/TheOtherRolesAU/TheOtherRoles/blob/main/TheOtherRoles/Modules/CustomHats.cs#L529

**Comment by TianMengLucky** [comment]
Oh, I understand. Thank you for your answer. I originally knew how to obtain reshash, but I didn't know what reshasha, reshashc, etc. meant. But after listening to your answer, I understand&nbsp;












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Wed, Nov 30, 2022 01:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TheOtherRolesAU/TheOtherHats] A question (for help) (Issue #4)




   
I think "reshash" means "resource hash"
 The value of parameter "reshash" in json file is the MD5 value of your hat,
 "reshasha" means Main texture,  "reshashc" means Climb texture, and so on
 Every file has its own MD5 value, it just like its ID
 here shows how it use:https://github.com/TheOtherRolesAU/TheOtherRoles/blob/main/TheOtherRoles/Modules/CustomHats.cs#L529

**Comment by jellycooker** [comment]
> 

能留个联系方式吗？交流一下。邮箱或tg都行。
